services:
  flask:
    build: .
    ports:
      - "5050:5000"
    environment:
      FLASK_ENV: development
      TWILIO_ACCOUNT_SID: 1234567890
      TWILIO_AUTH_TOKEN: 1234567890
      TWILIO_PHONE_NUMBER: +15556667777
      ADMIN_PHONE_NUMBER: +15556667777
      API_KEY: ABCDEFG
    volumes:
      - ./app:/app
