services:

  jellyseer-twilio-webhook:
    image: ghcr.io/dobsondev/jellyseer-twilio-webhook:latest
    container_name: jellyseer-twilio-webhook
    environment:
      - TWILIO_ACCOUNT_SID=1234567890
      - TWILIO_AUTH_TOKEN=1234567890
      - TWILIO_PHONE_NUMBER=+15556667777
      - ADMIN_PHONE_NUMBER=+15556667777
      - AUTH_HEADER=ABCDEFG
    ports:
      - "5050:5000"
    restart: unless-stopped
