services:
  flask:
    build: .
    ports:
      - "5050:5000"
    environment:
      FLASK_ENV: development
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      ADMIN_PHONE_NUMBER: ${ADMIN_PHONE_NUMBER}
      AUTH_HEADER: ${AUTH_HEADER}
    volumes:
      - ./app:/app
