services:
  flask:
    build: .
    ports:
      - "5050:5000"
    environment:
      FLASK_ENV: development
      TWILIO_ACCOUNT_SID: ${TWILIO_TEST_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_TEST_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: +15005550006 
      ADMIN_PHONE_NUMBER: +12025550123
      AUTH_HEADER: ABCDEFG
      JELLYSEER_URL: https://jellyseer.example.com
    volumes:
      - ./app:/app
