name: Build and Test Application

on:
  pull_request: 
    branches: [ "main" ]

jobs:
  build:
    name: Build Application with Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run `docker compose build --no-cache`
      run: |
        docker compose -f docker-compose.github.yml build --no-cache

    - name: Run `docker compose up`
      run: |
        docker compose -f docker-compose.github.yml up -d

    - name: Run `docker compose down`
      run: |
        docker compose -f docker-compose.github.yml down

  run-postman-collection:
    name: Run Postman Collection Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run `docker compose build --no-cache`
      run: |
        docker compose -f docker-compose.github.yml build --no-cache

    - name: Run `docker compose up`
      run: |
        docker compose -f docker-compose.github.yml up -d

    - name: Install Newman
      run: |
        sudo npm install -g newman

    - name: Run Postman Collection tests with Newman
      run: |
        newman run postman/postman_collection.json --delay-request 1000

    - name: Run `docker compose down`
      run: |
        docker compose -f docker-compose.github.yml down
