name: Build and Publish Latest Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish-latest:
    name: Build Image and Publish Image with Latest Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:latest