name: Create Release on Semantic Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get previous tag (if exists)
      id: prev_tag
      run: |
        # Get the most recent tag before the pushed tag. If none exists, fallback to empty.
        prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        echo "::set-output name=tag::$prev_tag"

    - name: Generate Release Notes
      id: generate_notes
      run: |
        if [ "${{ steps.prev_tag.outputs.tag }}" = "" ]; then
          # No previous tag, show all commit messages
          release_notes=$(git log --oneline)
        else
          # Get commit messages between the previous tag and the new tag
          release_notes=$(git log ${{ steps.prev_tag.outputs.tag }}..${{ github.ref_name }} --oneline)
        fi
        echo "::set-output name=notes::$release_notes"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # The pushed tag
        release_name: ${{ github.ref_name }}  # Use the tag name as the release name
        body: |
          Release notes for version ${{ github.ref_name }}:
          ${{ steps.generate_notes.outputs.notes }}
        draft: false
        prerelease: false